services:
  gateway-service:
    build: .
    networks:
      - shared-network
    ports:
      - "8080:8080"
    container_name: gateway-service
    environment:
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY} # Integration line: Auth
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
networks:
  shared-network:
    external: true
