# Application name
spring.application.name=${SPRING_APPLICATION_NAME:gatewayservice}

# Server host domains
hosts=${HOSTS:main=localhost:8080}

# Server port - Set to 8443 for HTTPS traffic
server.port=${SERVER_PORT:8080}

# HTTPS certificate settings
#server.ssl.enabled=${SERVER_SSL_ENABLED:true}
#server.ssl.key-store=${SERVER_SSL_KEY_STORE:file:/gatewayservice/certs/keystore.p12}
#server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD:changeit}
#server.ssl.key-store-type=${SERVER_SSL_KEY_STORE_TYPE:PKCS12}

# CORS origins
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:6080}
