spring.application.name=gatewayservice

server.port = 8080

#Below are the settings needed for hosting via HTTPS, you must generate a .p12 certificate
#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store=file:/app/certs/keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:6080}

accessSecretKey = ${ACCESS_SECRET_KEY}